const inventory =
[
{ 
id: 1, 
name: A, 
price: 100, 
collection: "summer -19",
type: "Mobilskal",
material: "papper",
image: "", 
},
{ 
    id: 2, 
    name: B, 
    price: 249, 
    collection: "fall -18",
    type: "Plånboksskal",
    material: "glas", 
    image: "", 
},
{ 
    id: 3, 
    name: C, 
    price: 500, 
    collection: "summer -17",
    type: "Mobilskal",
    material: "plast", 
    image: "", 
},
{ 
    id: 4, 
    name: D, 
    price: 699, 
    collection: "spring -19",
    type: "Plånboksskal",
    material: "titan", 
    image: "", 
},
{ 
    id: "5", 
    name: "Wild Blossom", 
    price: 399, 
    collection: "Negin Mirsalehi",
    type: "Mobilskal",
    material: "Plast", 
    image: "https://ideal-products-production.imgix.net/images/2545_be2242a92c-idfcng-ixs-144_1-original.jpg?w=720&auto=format&fit=clip",
    },
    { 
        id: "6", 
        name: "Crayon Bird", 
        price: 299, 
        collection: "La Escuela iDeal",
        type: "Mobilskal",
        material: "Plast",
        image: "https://ideal-products-production.imgix.net/images/2990_0dce89309f-idfcei-ixs-140_1-original.jpg?w=576&auto=format&fit=clip", 
    },
    { 
        id: "7", 
        name: "Green Velvet", 
        price: 499, 
        collection: "Mayfair Clutch",
        type: "Plånboksskal",
        material: "Sammet och mikrofibrer",
        image: "https://ideal-products-production.imgix.net/images/320_2617602a1e-idmcv-i8-100_1-original.jpg?w=576&auto=format&fit=clip", 
    },
    { 
        id: "8", 
        name: "Black", 
        price: 399, 
        collection: "Swipe Wallet",
        type: "Plånboksskal",
        material: "Läder",
        image: "https://ideal-products-production.imgix.net/images/793_c65bd4f380-idswip5spp03_4-original.jpg?w=576&auto=format&fit=clip", 
    }
]